#include "uav.h"
#include "link_sortin.h"

/*
 ******************************************************************************
 * DEFINES
 ******************************************************************************
 */

/*
 ******************************************************************************
 * EXTERNS
 ******************************************************************************
 */
extern mavlink_system_t mavlink_system_struct;

extern Mailbox mavlink_param_set_mb;
extern Mailbox mavlink_command_long_mb;
extern Mailbox controller_mb;
extern Mailbox mission_mb;

/*
 ******************************************************************************
 * GLOBAL VARIABLES
 ******************************************************************************
 */
static mavlink_param_set_t              mavlink_param_set_struct;
static mavlink_param_request_list_t     mavlink_param_request_list_struct;
static mavlink_param_request_read_t     mavlink_param_request_read_struct;
static mavlink_command_long_t           mavlink_command_long_struct;
static mavlink_manual_control_t         mavlink_manual_control_struct;
static mavlink_set_mode_t               mavlink_set_mode_struct;

static mavlink_mission_request_list_t   mavlink_mission_request_list_struct;
static mavlink_mission_request_t        mavlink_mission_request_struct;
static mavlink_mission_item_t           mavlink_mission_item_struct;
static mavlink_mission_clear_all_t      mavlink_mission_clear_all_struct;
static mavlink_mission_count_t          mavlink_mission_count_struct;
static mavlink_mission_ack_t            mavlink_mission_ack_struct;
static mavlink_mission_set_current_t    mavlink_mission_set_current_struct;

static Mail param_set_mail      = {NULL, MAVLINK_MSG_ID_PARAM_SET,      NULL};
static Mail command_long_mail   = {NULL, MAVLINK_MSG_ID_COMMAND_LONG,   NULL};
static Mail manual_control_mail = {NULL, MAVLINK_MSG_ID_MANUAL_CONTROL, NULL};
static Mail set_mode_mail       = {NULL, MAVLINK_MSG_ID_SET_MODE,       NULL};
static Mail mission_mail        = {NULL, MAVLINK_MSG_ID_MISSION_REQUEST,NULL};

/*
 *******************************************************************************
 * LOCAL FUNCTIONS
 *******************************************************************************
 */

#include "link_sortin_autogenerated.c"

/*
 *******************************************************************************
 * Old junk for hystorical purpose
 *******************************************************************************
 */
#define SORTINCASE(lowercase, UPPERCASE, m){                                          \
    case MAVLINK_MSG_ID_##UPPERCASE:                                                  \
      mavlink_msg_##lowercase##_decode(msg, &mavlink_##lowercase##_struct);           \
      if (mavlink_##lowercase##_struct.target_system != mavlink_system_struct.sysid)  \
        return LINK_SUCCESS; /* silently ignore messages not for this system */       \
      if (m##_mail.payload == NULL){                                                  \
        m##_mail.invoice = MAVLINK_MSG_ID_##UPPERCASE ;                               \
        m##_mail.payload = &mavlink_##lowercase##_struct;                             \
        status = chMBPost(&mavlink_##m##_mb, (msg_t)&m##_mail, TIME_IMMEDIATE);       \
        if (status != RDY_OK)                                                         \
          return LINK_FAILED;                                                         \
      }                                                                               \
      else                                                                            \
        return LINK_SUCCESS;                                                          \
      break;                                                                          \
}
