/* 
!!! Atomatically generated by
src/link/gen_link_unpacker.py
Do not edit it manually. 
*/
#include "uav.h"

extern GlobalFlags_t GlobalFlags;
extern mavlink_system_t                   mavlink_system_struct;

extern mavlink_param_set_t mavlink_param_set_struct;
extern EventSource event_mavlink_in_param_set;


/**
 *
 */
void UnpackCycle(SerialDriver *sdp){
  mavlink_message_t msg;
  mavlink_status_t status;
  msg_t c = 0;
  msg_t prev_c = 0;

  while (!chThdShouldTerminate()) {
    c = sdGetTimeout((SerialDriver *)sdp, MS2ST(50));
    if (c != Q_TIMEOUT){
      if (mavlink_parse_char(MAVLINK_COMM_0, (uint8_t)c, &msg, &status)) {
        switch(msg.msgid){
        case MAVLINK_MSG_ID_PARAM_SET:
          mavlink_msg_param_set_decode(&msg, &mavlink_param_set_struct);
          if (mavlink_param_set_struct.target_system == mavlink_system_struct.sysid)
            chEvtBroadcastFlags(&event_mavlink_in_param_set, EVMSK_MAVLINK_IN_PARAM_SET);
          break;

        default:
          break;
        }
      }
    }
  }
}
